/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input wire [7:0] r_input
    , input wire [7:0] in_out_put

      // Outputs
    , output wire [7:0] result
    );


  assign result = ~ r_input;


endmodule

